title: Expect Dialog CA
#logo: /assets/img/logo.png
description: This repository contains scripts meant to make managing an openssl ca less painful inside a terminal environment
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
